name: "🐛 Bug Report"
description: "Report a bug to help us improve the project"
title: "[BUG] "
labels: ["bug", "needs-triage"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        ## 🐛 Thanks for reporting a bug!
        
        We appreciate you taking the time to report this issue. Please provide as much detail as possible to help us reproduce and fix the bug quickly.

  - type: checkboxes
    id: prerequisites
    attributes:
      label: "Prerequisites"
      description: "Please confirm you have completed the following"
      options:
        - label: "I have searched existing issues to ensure this bug hasn't been reported before"
          required: true
        - label: "I have updated to the latest version of the project"
          required: true
        - label: "I have read the troubleshooting documentation"
          required: true

  - type: textarea
    id: bug-description
    attributes:
      label: "🔍 Bug Description"
      description: "Provide a clear and concise description of what the bug is"
      placeholder: |
        Describe what happened and what you expected to happen:
        
        • What is the current (incorrect) behavior?
        • What should the correct behavior be?
        • When did this issue start occurring?
    validations:
      required: true

  - type: textarea
    id: reproduction-steps
    attributes:
      label: "🔄 Steps to Reproduce"
      description: "Provide detailed steps to reproduce the issue"
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
        
        Be as specific as possible. Include any relevant data, inputs, or configuration.
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: "✅ Expected Behavior"
      description: "What did you expect to happen?"
      placeholder: |
        Clearly describe what you expected to happen instead of the bug.
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: "❌ Actual Behavior"
      description: "What actually happened?"
      placeholder: |
        Describe what actually happened, including any error messages, unexpected outputs, or incorrect behavior.

  - type: dropdown
    id: severity
    attributes:
      label: "🚨 Severity"
      description: "How severe is this bug?"
      options:
        - "Low - Minor issue, workaround available"
        - "Medium - Affects functionality but not critical"
        - "High - Major functionality broken"
        - "Critical - Application unusable or data loss"
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: "🖥️ Environment Information"
      description: "Please provide details about your environment"
      placeholder: |
        • Operating System: (e.g., Windows 11, macOS 13.0, Ubuntu 22.04)
        • Browser: (e.g., Chrome 118, Firefox 119, Safari 17)
        • Project Version: (e.g., v1.2.3)
        • Node.js Version: (if applicable)
        • Other relevant software versions:
      render: markdown

  - type: textarea
    id: error-logs
    attributes:
      label: "📋 Error Logs"
      description: "Include any relevant error messages, stack traces, or console output"
      placeholder: |
        Paste any error messages, stack traces, or console output here.
        
        ```
        Error messages go here
        ```
      render: shell

  - type: textarea
    id: screenshots
    attributes:
      label: "📸 Screenshots"
      description: "Add screenshots to help explain the problem (if applicable)"
      placeholder: |
        Drag and drop screenshots here, or use the toolbar to upload images.

  - type: textarea
    id: additional-context
    attributes:
      label: "📝 Additional Context"
      description: "Add any other context about the problem"
      placeholder: |
        • Does this happen consistently or intermittently?
        • Are there any workarounds you've found?
        • Any other relevant information that might help us debug this issue?

  - type: checkboxes
    id: contribution
    attributes:
      label: "🤝 Contribution"
      description: "Are you interested in helping fix this bug?"
      options:
        - label: "I'm willing to submit a pull request to fix this bug"
        - label: "I can help with testing the fix"
        - label: "I'm available to provide additional information if needed"